# .goreleaser.yml
version: 2

builds:
  - id: quantumd
    dir: ./quantumd
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=musl,netgo,sqlite_omit_load_extension
    ldflags:
      - -s -w -X github.com/threefoldtech/quantum-storage/quantumd/cmd.Version={{.Version}} -X github.com/threefoldtech/quantum-storage/quantumd/cmd.Commit={{.Commit}} -X github.com/threefoldtech/quantum-storage/quantumd/cmd.Date={{.Date}}
      - -extldflags "-static"

  - id: zstor-metadata-decoder
    builder: rust
    dir: ./zstor-metadata-decoder
    binary: zstor-metadata-decoder
    command: build
    targets:
      - x86_64-unknown-linux-musl
    hooks:
      pre:
        - cmd: sed -i 's/version = "0.0.0"/version = "{{.Version}}"/' Cargo.toml
          dir: ./zstor-metadata-decoder

archives:
  - id: quantumd
    ids: ["quantumd"]
    formats: ["binary", "tar.gz"]
    name_template: "quantumd_{{ .Os }}_{{ .Arch }}"
  - id: zstor-metadata-decoder
    ids: ["zstor-metadata-decoder"]
    formats: ["binary", "tar.gz"]
    name_template: "zstor-metadata-decoder_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "quantum-storage"
