# Quantum Storage Daemon Configuration
network: main # dev, test, or main
mnemonic: "" # Your ThreeFold mnemonic

# Deployment configuration
deployment_name: "" # Will be publicly visible
password: "" # Used along with mnemonic to encrypt data and protect zdbs

# Backend configuration
meta_nodes: [11, 13, 24, 2011] # List of node IDs for metadata ZDBs
data_nodes: [11, 13, 24, 2011] # List of node IDs for data ZDBs
meta_size_gb: 1 # Size in GB for metadata ZDBs
data_size_gb: 10 # Size in GB for data ZDBs

# Zstor configuration
min_shards: 2
expected_shards: 4
# zdb_connection_type: "mycelium" # optional, can be "mycelium", "ipv6", "ygg". defaults to mycelium
# zdb_data_size: "2G" # optional, size of the zdb data directory in MB or GB. defaults to 2560M

# Paths
zdb_root_path: "/data"
qsfs_mountpoint: "/mnt/qsfs"

# Daemon configuration
retry_interval: 10m # Interval for retrying failed uploads (e.g., 5m, 10m, 1h)
zdb_rotate_time: 15m # Time interval for rotating ZDB data files
